title: Personal Blog
description: My Personal Blog
author: Jacky Fan
github: https://github.com/fanq10
about: A reliable Cloud Engineer working at Amazon Web Services
disqus_shortname: stackproblems
google_analytics: UA-313403853-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
    - icon: fa-twitter
      link: "fanq10"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/fanq10"
#    - icon: fa-stack-exchange
#      link: "#"
    - icon: fa-github
      link: "https://github.com/fanq10"

share:
  twitter_username: fanq10
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://fanq10.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
